### ISSUE TITLE
Deployment is failing

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/pythia-cookoff-2025#2]
https://github.com/ProjectPythia/pythia-cookoff-2025/actions/runs/13526740956/job/37799210401

**Comment by brian-rose** [comment]
I just enabled "read and write permissions" for workflows for this repository. That should resolve the deployment problems.

**Comment by jukent** [comment]
Thanks

Rerunning the actions now

**Comment by jukent** [comment]
Deployment passed! But the styling is still an issue. Sometimes it just takes a moment. I'll open a new PR for the theme issue.

![Image](https://github.com/user-attachments/assets/e5107cbf-f505-4bd6-9c65-c5fe3cda4fcd)
